### ISSUE TITLE
PHPStan does static analysis

### ISSUE THREAD

**Issue by szepeviktor** [wptavern/the-tavern#1]
Hello! a lot of strange things are going on.

e.g. missing `Tavern\Layout\LoopLayout` and `Tavern\Settings\Options`
on higher Levels - e.g. 6 - you will get robust code.

`phpstan.neon.dist`

```yaml
#$ composer require --dev szepeviktor/phpstan-wordpress
#$ vendor/bin/phpstan analyse -l 4

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/app/
    autoload_files:
        - %currentWorkingDirectory%/app/bootstrap-compat.php
        - %currentWorkingDirectory%/app/functions-assets.php
        - %currentWorkingDirectory%/app/functions-filters.php
        - %currentWorkingDirectory%/app/functions-helpers.php
        - %currentWorkingDirectory%/app/functions-setup.php
        - %currentWorkingDirectory%/app/functions-template.php
        - %currentWorkingDirectory%/app/functions-woocommerce.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters invoked with [34567] parameters, 2 required\.$#'
        # Uses __callStatic()
        - '#^Call to static method resolve\(\) on an unknown class Hybrid\\App\.$#'
```
